#!/usr/bin/env python3
"""
gen_parser.py — turn a confirmed fieldmap JSON into a runnable Python parser.

Once you've confirmed the record layout (via csv_correlate and/or
field_probe) you codify it as a small JSON fieldmap (see
references/fieldmap_schema.md for the format and references/
dg388_fieldmap.json for a complete example). This tool emits a single-file
Python parser that:

    * reads the binary file
    * unpacks each record with struct
    * applies any scale factors and decodes dates/times
    * skips blank/invalid records per the rules in the fieldmap
    * emits CSV on stdout (or to a file)
    * has no third-party dependencies

Usage:
    python gen_parser.py fieldmap.json > parser.py
    python gen_parser.py fieldmap.json -o parser.py
"""

import argparse
import json
import sys
from pathlib import Path


# struct format characters for each fieldmap type
STRUCT_CHAR = {
    "u8":  "B", "i8":  "b",
    "u16": "H", "i16": "h",
    "u32": "I", "i32": "i",
    "u64": "Q", "i64": "q",
    "f32": "f", "f64": "d",
}


def build_record_struct(fields, endianness, record_size):
    """
    Build a struct format string that covers the whole record. Handles gaps
    (reserved bytes) by padding with 'x' bytes.
    """
    prefix = "<" if endianness == "little" else ">"
    pieces = []
    cursor = 0
    value_fields = []  # list of (name, scale, type, encoding) in order

    for f in sorted(fields, key=lambda x: x["offset"]):
        if f["offset"] > cursor:
            pieces.append(f"{f['offset'] - cursor}x")
            cursor = f["offset"]
        t = f["type"]
        if t == "bytes":
            pieces.append(f"{f['size']}s")
        elif t == "utf8":
            pieces.append(f"{f['size']}s")
        elif t == "pad":
            pieces.append(f"{f['size']}x")
            cursor += f["size"]
            continue
        elif t in STRUCT_CHAR:
            pieces.append(STRUCT_CHAR[t])
        else:
            raise ValueError(f"unknown type {t}")
        value_fields.append(f)
        cursor += f["size"]

    if cursor < record_size:
        pieces.append(f"{record_size - cursor}x")

    return prefix + "".join(pieces), value_fields


PARSER_TEMPLATE = '''#!/usr/bin/env python3
"""
Auto-generated parser for {format_name}.

{description}

Generated by binary-format-reverser / gen_parser.py from a confirmed
fieldmap. Safe to edit; re-generating will overwrite your edits, so copy
to a new filename first if you customize it.
"""

import csv
import struct
import sys
from pathlib import Path

RECORD_SIZE = {record_size}
RECORD_STRUCT = {record_struct!r}
FILE_HEADER_SIZE = {file_header_size}

FIELD_NAMES = {field_names!r}


def parse_file(path):
    """Yield one dict per valid record."""
    data = Path(path).read_bytes()
    if FILE_HEADER_SIZE:
        data = data[FILE_HEADER_SIZE:]

    if len(data) % RECORD_SIZE:
        remainder = len(data) % RECORD_SIZE
        print(f"Warning: trailing {{remainder}} bytes beyond last "
              f"complete record", file=sys.stderr)

    n = len(data) // RECORD_SIZE
    for i in range(n):
        base = i * RECORD_SIZE
        raw = struct.unpack_from(RECORD_STRUCT, data, base)
        values = dict(zip(FIELD_NAMES, raw))
{skip_block}
{decode_block}
        yield values


def main():
    if len(sys.argv) < 2:
        print(f"usage: {{sys.argv[0]}} <input.bin> [output.csv]",
              file=sys.stderr)
        sys.exit(1)
    in_path = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 \\
        else Path(in_path).with_suffix(".csv")

    with open(out_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(FIELD_NAMES)
        for rec in parse_file(in_path):
            w.writerow([rec[k] for k in FIELD_NAMES])
    print(f"wrote {{out_path}}")


if __name__ == "__main__":
    main()
'''


def build_skip_block(fieldmap):
    """Generate skip-record-if-blank code from the fieldmap's validation rules."""
    rules = fieldmap.get("skip_blank", {})
    if not rules:
        return ""

    lines = []
    if rules.get("all_zero"):
        # Read raw bytes and check all-zero
        lines.append('        if all(v == 0 or v == b"\\x00" '
                     '* (len(v) if isinstance(v, bytes) else 0) '
                     'for v in values.values()):')
        lines.append('            continue')
    if "field_zero" in rules:
        for fname in rules["field_zero"]:
            lines.append(f'        if values.get({fname!r}) == 0:')
            lines.append('            continue')
    return "\n".join(lines)


def build_decode_block(fields):
    """Generate post-processing: scale factors, date/time decoding, etc."""
    lines = []
    for f in fields:
        name = f["name"]
        encoding = f.get("encoding")
        scale = f.get("scale")
        if scale and scale != 1:
            lines.append(f'        values[{name!r}] = '
                         f'values[{name!r}] / {scale}')
        if encoding == "YYYYMMDD":
            lines.append(f'        v = int(values[{name!r}])')
            lines.append(f'        values[{name!r}] = '
                         f'f"{{v//10000:04d}}-{{(v//100)%100:02d}}-{{v%100:02d}}"')
        elif encoding == "HHMMSS":
            lines.append(f'        v = int(values[{name!r}])')
            lines.append(f'        values[{name!r}] = '
                         f'f"{{v//10000:02d}}:{{(v//100)%100:02d}}:{{v%100:02d}}"')
        elif encoding == "unix_seconds":
            lines.append(f'        import datetime')
            lines.append(f'        values[{name!r}] = '
                         f'datetime.datetime.utcfromtimestamp('
                         f'values[{name!r}]).isoformat() + "Z"')
        elif encoding == "ddmm":
            # NMEA DDMM.MMMM -> decimal degrees. Preserves sign for
            # southern/western hemispheres.
            lines.append(f'        _v = values[{name!r}]')
            lines.append(f'        _sign = -1.0 if _v < 0 else 1.0')
            lines.append(f'        _v = abs(_v)')
            lines.append(f'        _deg = int(_v / 100)')
            lines.append(f'        values[{name!r}] = '
                         f'_sign * (_deg + (_v - _deg * 100) / 60.0)')
    return "\n".join(lines) if lines else "        pass"


def main():
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument("fieldmap", help="JSON fieldmap file")
    ap.add_argument("-o", "--output", help="where to write parser.py")
    args = ap.parse_args()

    fm = json.loads(Path(args.fieldmap).read_text())
    struct_fmt, value_fields = build_record_struct(
        fm["fields"], fm.get("endianness", "little"), fm["record_size"])

    field_names = [f["name"] for f in value_fields]

    code = PARSER_TEMPLATE.format(
        format_name=fm.get("format_name", "unknown"),
        description=fm.get("description", "").replace('"""', "'''"),
        record_size=fm["record_size"],
        record_struct=struct_fmt,
        file_header_size=fm.get("file_header_size", 0),
        field_names=field_names,
        skip_block=build_skip_block(fm),
        decode_block=build_decode_block(value_fields),
    )

    if args.output:
        Path(args.output).write_text(code)
        print(f"wrote {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(code)


if __name__ == "__main__":
    main()
